openapi: 3.0.3
info:
  version: 1.0.0
  title: Airspace API
  x-logo:
    url: >-
      https://camo.githubusercontent.com/b0c3504953b38611e4256f081275c7a23b56981e62942a99f0f906db69e801f9/68747470733a2f2f692e6962622e636f2f6e6e575133624e2f41495253504143452d4f52414e47452e706e67
    href: 'https://cbsinteractive.github.io/airspace/'
  description: CDN Video Management API
  contact:
    name: Video Technology Group - Video Delivery and Experience
    email: vde@cbsinteractive.com
    url: 'https://cbsinteractive.github.io/airspace/'
  license:
    name: Proprietary
tags:
  - name: Organizations
    description: 'Organizations are parent entities for Airspace properties. EG: CBSN'
  - name: Miscellaneous
    description: 'Miscellaneous operations.'
  - name: Purge
    description: 'Purge operations.'
  - name: Configurations
    description: 'Configurations are Airspace properties. Identified by and Airspace config_id.'
paths:
  /healthcheck:
    get:
      description: Service health check
      operationId: healthCheck
      x-ts-operationId: healthCheck
      tags:
        - Miscellaneous
  '/purge/{config_id}':
    servers:
      - url: https://airspace-purge.cbsivideo.com/v1
        description: Production Purging Server
    post:
      summary: Create A Purge Operation
      description: Creates a purge operation for an Airspace property.
      operationId: createPurge
      x-ts-operationId: createPurge
      tags:
        - Purge
      security:
        - authheader:
          - api
  '/config/{config_id}/dictionary/{dictionary_name}':
    get:
      summary: Return an edge dictionary.
      description: Return a Fastly edge dictionary.
      operationId: getEdgeDictionary
      x-ts-operationId: getEdgeDictionary
      tags:
        - EdgeDictionary
      security:
        - authheader:
            - api
    delete:
      summary: Delete a key in an edge dictionary.
      description: Delete a key in the configuration's Fastly edge dictionary.
      operationId: deleteEdgeDictionaryItem
      x-ts-operationId: deleteEdgeDictionaryItem
      tags:
        - EdgeDictionary
      security:
        - authheader:
            - api
    put:
      summary: Upsert a key into an edge dictionary.
      description: Upserts a key into the configuration's Fastly edge dictionary.
      operationId: upsertEdgeDictionaryItem
      x-ts-operationId: upsertEdgeDictionaryItem
      tags:
        - EdgeDictionary
      security:
        - authheader:
            - api
  /organizations:
    get:
      summary: Retrieve all Airspace organizations
      description: Returns a list of all organizations that are present in Airspace.
      operationId: getAllOrganizations
      x-ts-operationId: getAllOrganizations
      security:
        - authheader:
            - 'api:read'
      tags:
        - Organizations
    post:
      summary: Create an Organization
      description: Creates an organizations for use in Airspace.
      operationId: createOrganization
      x-ts-operationId: createOrganization
      security:
        - authheader:
            - api
      tags:
        - Organizations
  '/organizations/{organization_id}':
    get:
      summary: Get an Organization
      description: Returns a single organization.
      operationId: getOrganization
      x-ts-operationId: getOrganization
      security:
        - authheader:
            - 'api:read'
      tags:
        - Organizations
  '/organizations/{organization_id}/configs':
    get:
      summary: Get a list of configs per Organization
      description: Returns a list of configs
      operationId: getOrganizationConfigs
      x-ts-operationId: getOrganizationConfigs
      security:
        - authheader:
            - 'api:read'
      tags:
        - Configurations
    post:
      summary: Create a new Config
      description: Create a new CDN configuration within this Organization.
      operationId: createConfig
      x-ts-operationId: createConfig
      security:
        - authheader:
            - 'api'
      tags:
        - Configurations
  '/organizations/{organization_id}/configs/{config_id}':
    patch:
      summary: Patch an existing Config
      description: Patch an existing configuration within this Organization.
      operationId: patchConfig
      x-ts-operationId: patchConfig
      security:
        - authheader:
            - 'api'
      tags:
        - Configurations
    get:
      summary: Get a single config
      operationId: getConfig
      x-ts-operationId: getConfig
      security:
        - authheader:
          - 'api:read'
      tags:
        - Configurations
components:
  securitySchemes:
    authheader:
      type: apiKey
      in: header
      name: Authorization
servers:
  - url: https://airspace.cbsivideo.com/v1
    description: Production Server
